import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Base directory where Prisma Generator outputs (The "schemas" folder)
const SCHEMAS_ROOT = path.join(__dirname, '../src/generated/zod/schemas');

// Where we want to save the clean export files
const OUTPUT_ROOT = path.join(__dirname, '../src/generated/zod');

// 1. Define our two targets
const TARGETS = [
  {
    source: path.join(SCHEMAS_ROOT, 'enums'),
    output: path.join(OUTPUT_ROOT, 'enums.ts'),
    label: 'Enums',
  },
  {
    source: path.join(SCHEMAS_ROOT, 'models'),
    output: path.join(OUTPUT_ROOT, 'models.ts'),
    label: 'Models',
  },
];

const generateBarrels = () => {
  if (!fs.existsSync(SCHEMAS_ROOT)) {
    console.log(`⚠️ Schemas directory not found at ${SCHEMAS_ROOT}. Run prisma generate first.`);
    return;
  }

  TARGETS.forEach(({ source, output, label }) => {
    console.log(`🔍 Scanning ${label} in: ${source}`);

    if (!fs.existsSync(source)) {
      console.log(`   ⚠️ Source folder missing: ${source}`);
      return;
    }

    const files = fs.readdirSync(source);

    // Filter .ts files, ignore index/d.ts
    const exportFiles = files
      .filter((file) => file.endsWith('.ts') && !file.endsWith('index.ts') && !file.endsWith('.d.ts'))
      .map((file) => path.join(source, file));

    if (exportFiles.length === 0) {
      console.log(`   ⚠️ No files found for ${label}.`);
      return;
    }

    const exports = exportFiles.map((file) => {
      // Calculate relative path from the OUTPUT file to the SOURCE file
      let relativePath = path.relative(path.dirname(output), file).replace(/\.ts$/, '');

      // Normalize for Windows
      relativePath = relativePath.split(path.sep).join('/');

      if (!relativePath.startsWith('.')) {
        relativePath = `./${relativePath}`;
      }

      return `export * from '${relativePath}';`;
    });

    const header = `// Auto-generated by scripts/generate-barrel.js\n`;
    fs.writeFileSync(output, header + exports.join('\n'));
    console.log(`✅ Generated ${label} barrel at ${output} (${exports.length} exports)`);
  });
};

generateBarrels();
